import { Dimensions, StyleSheet } from "react-native";
import { Colors } from "./Colors";
export const { width, height } = Dimensions.get("window");

const Styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 40,
    paddingHorizontal: 10,
  },
  centeredView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  modalButton: {
    alignSelf: "center",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  googleButton: {
    width: "90%",
    flexDirection: "row",
    justifyContent: "center",
    alignSelf: "center",
    padding: 15,
    borderWidth: 1,
    borderColor: Colors.dark.icon,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 10,
  },
  downloadBtn: {
    backgroundColor: Colors.dark.icon,
    width: width * 0.4,
    padding: 10,
    alignItems: "center",
    borderRadius: 5,
    justifyContent: "center",
    flexDirection: "row",
    rowGap: 10,
    height: height * 0.05,
  },
  googleButtonText: {
    color: "#007bff",
    fontSize: 16,
    fontWeight: "bold",
  },
  iconTextButton: {
    width: "20%",
    height: "100%",
  },
  genreImage: {
    width: width,
    height: height * 0.45,
    backgroundColor: "transparent",
  },
  genreGradient: {
    position: "absolute",
    bottom: 0,
    top: 1,
    left: 0,
    right: 0,
    height: height * 0.45,
  },
  authButtons: {
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    width: "90%",
    height: height * 0.06,
    borderRadius: 12,
  },
  modalContent: {
    minWidth: width * 0.8,
    maxWidth: width * 0.95,
    borderRadius: 20,
    padding: 5,
    height: height * 0.45,
  },
  modalBodyText: {
    fontSize: 9,
    width: width * 0.6,
    borderColor: "grey",
    lineHeight: 14,
    fontWeight: "bold",
  },
  modalBodyContainer: {
    flexDirection: "row",
    backgroundColor: "transparent",
    gap: 5,
    alignItems: "center",
    paddingLeft: 30,
    paddingBottom: 5,
  },
  avatarBtn: {
    height: 40,
    backgroundColor: "grey",
    width: 40,
    borderRadius: 1000,
  },
  roundib: {},
  textInput: {
    marginTop: 10,
    paddingHorizontal: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "rgba(189, 187, 187, 0.47)",
    width: "90%",
    height: height * 0.06,
    borderRadius: 8,
    borderColor: Colors.dark.icon,
    alignSelf: "center",
  },
  statusCard: {
    alignItems: "center",
    justifyContent: "center",
    borderColor: "black",
    alignSelf: "center",
    width: width * 0.93,
    borderRadius: 12,
    height: height * 0.2,
  },
  textInputField: {
    width: "90%",
    height: "100%",
  },
  headerButtons: {
    backgroundColor: "rgb(240,240,240)",
    height: 40,
    width: 40,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 1000,
    // paddingBottom: 5,
    elevation: 2,
  },
  logoImage: {
    borderRadius: 1000,
    maxWidth: 120,
    maxHeight: 120,
    alignSelf: "center",
  },
});
export default Styles;
